### ISSUE TITLE
Dashboard - Main Task List

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/misinfo-dashboard#3]
### General

- [ ] DOCS @lh34682 
- [x] Trello Board to GitHub Issues @lh34682 

### Create Report

- [ ] Topic & Source - finalize the custom other tags & change "Otro/Other" to only "Other" on the dashboard. @an29454 
- [ ] Geolocation - as of now agencies only need to provide us their city and state, but in the future we will need their full address in order to set a pin for the location radius (ex. 100 mile radius).
- [ ] Login page - "Team name" should just be a "Name" input. @je27699 
- [ ] Testing & found that on the dashboard creating a report, the image uploaded did not save to the database :( 

### Agency
- [ ] Allow agency the ability to add other “Agency” users

### Agency Users

- [ ] `ReportsSection.jsx` - report list should only show reports for the agency user logged in. @je27699 
- [ ] `Users.jsx` - users in table list should only be user's who have created a report for the agency  (logged in agency user) @lh34682 

### Archive tasks

- [ ] Create a Spanish version of the user add report on the website. [#81](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/81)
- [ ] [Images don't show in More Information](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/60)
- [ ] [New User Sign Up #61](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/61)
- [ ] [Dev Documentation and Readme file #62](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/62)
- [ ] [Agency Address](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/63) - Geolocation - as of now agencies only need to provide us their city and state, but in the future we will need their full address in order to set a pin for the location radius (ex. 100 mile radius).
- [ ] Login/Signup ext - one click #74
- [ ] [Login/Signup - New Agency Request #76](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/76)
- [ ] [MEETING NOTES: Items to discuss - 02/06/2024 #78](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/78)
- [ ] [Geolocation - User's State #82](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/82)
- [ ] [Dashboard Analytics - Should be collecting data #83](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/83)

### Talia Business Questions

- [ ] Reporting doesn’t need to have selecting a location every time
