### ISSUE TITLE
Import Issues from caet-saga

### ISSUE THREAD

**Issue by luukee** [engagingnewsproject/misinfo-dashboard#8]
- [ ] Create a Spanish version of the user add report on the website. [#81](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/81)
- [ ] [Images don't show in More Information](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/60)
- [ ] [New User Sign Up #61](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/61)
- [ ] [Dev Documentation and Readme file #62](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/62)
- [ ] [Agency Address](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/63) - Geolocation - as of now agencies only need to provide us their city and state, but in the future we will need their full address in order to set a pin for the location radius (ex. 100 mile radius).
- [ ] Login/Signup ext - one click #74
- [ ] [Login/Signup - New Agency Request #76](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/76)
- [ ] [MEETING NOTES: Items to discuss - 02/06/2024 #78](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/78)
- [ ] [Geolocation - User's State #82](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/82)
- [ ] [Dashboard Analytics - Should be collecting data #83](https://github.austin.utexas.edu/caet-saga/misinfo-dashboard/issues/83)
- [ ]
